---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
spec:
  selector:
    matchLabels:
      app: name
  replicas: 1
  template:
    metadata:
      labels:
        app: name
    spec:
     containers:
     - name: name
       image: 
    ports:
     - containerPort: 8001


---

apiVersion: v1
kind: Service
metadata:
  name: name
  labels:
    app: name
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: "alb"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  selector:
    app: name

